### ISSUE TITLE
Bug encountered

### ISSUE THREAD

**Issue by snorthman** [texworld/betterbib#253]
```commandline
Syncing... ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  20% 0:03:12
No known latex representation for character: U+0203 - ‘ȃ’
No known latex representation for character: U+01E7 - ‘ǧ’
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "T:\Repos\fastmri-intervention\venv\Scripts\betterbib.exe\__main__.py", line 7, in <module>
  File "<string>", line 76, in main
  File "<string>", line 28, in run
  File "<string>", line 69, in sync
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<string>", line 185, in find_unique
KeyError: 'items'
```

and got result

```
% The entry below contains non-ASCII chars that could not be converted
% to a LaTeX equivalent.
@ARTICLE{Hossein_Hosseini2019-zx,
title = "{ACCELERATED} {CORONARY} {MRI} {USING} {3D} {SPIRIT-RAKI} {WITH} {SPARSITY} {REGULARIZATION}",
author = "Hossein Hosseini, Seyed Amir and Moeller, Steen and Weing{\"a}rtner, Sebastian and Uǧurbil, Kȃmil and Ak{\c c}akaya, Mehmet",
journal = "Proc. IEEE Int. Symp. Biomed. Imaging",
volume =  2019,
pages = "1692--1695",
month =  apr,
year =  2019,
keywords = "Coronary MRI; accelerated imaging; compressed sensing; deep learning; image reconstruction; machine learning; neural networks; parallel imaging",
language = "en"
}
```

**Comment by nschloe** [comment]
Thanks for the report! This will no longer crash now, but result in the warning
```
Warning: Hossein_Hosseini2019-zx: Could not find a positively unique match. Try 
manually adding a DOI to the entry.
```
Let's keep this open though to see if we're able to find the correct article at some point.

**Comment by nschloe** [comment]
This is completely fixed now.
