### ISSUE TITLE
ConnectionError newly installed betterbib does not work

### ISSUE THREAD

**Issue by chenyubi14** [texworld/betterbib#263]
Hi,

I installed betterbib with python 3.9.12 in anaconda, but it does not work with a ConnectionError.

I tried the default example in README.md
```
@article {krylov,
  author = {Liesen and Gaul and Nabben},
  title = {Framework Deflation Krylov Augmented}
}
```
I got the following error, and I have no idea what has happened. Could you take a look?
```
Syncing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9f29db0070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='openretractions.com', port=80): Max retries exceeded with url: /api/doi/10.1137/110820713/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f29db0070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yubichen/opt/miniconda3/bin/betterbib", line 8, in <module>
    sys.exit(main())
  File "<string>", line 28, in main
  File "<string>", line 13, in run
  File "<string>", line 45, in sync
  File "<string>", line 7, in check_retractions
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests_cache/session.py", line 115, in request
    return super().request(method, url, *args, **kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests_cache/session.py", line 147, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests_cache/session.py", line 189, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yubichen/opt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='openretractions.com', port=80): Max retries exceeded with url: /api/doi/10.1137/110820713/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f29db0070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by nschloe** [comment]
Dup of https://github.com/texworld/betterbib/issues/262.
