### ISSUE TITLE
AssertionError in _crossref_to_pybtex

### ISSUE THREAD

**Issue by cmungall** [texworld/betterbib#268]
```
✗ betterbib update  ~/Downloads/Reexport.bib  > ~/Downloads/reexport.enhanced.bib
Syncing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Warning: posted-content is not a supported type
Syncing... ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   2% -:--:--
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Warning: posted-content is not a supported type
Traceback (most recent call last):
  File "/Users/cjm/.local/bin/betterbib", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "<string>", line 3, in wrapper
  File "<string>", line 955, in _LrFvY
  File "<string>", line 3, in wrapper
  File "<string>", line 905, in _2zwPK
  File "<string>", line 3, in wrapper
  File "<string>", line 882, in _NgxMS
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 508, in find_unique
  File "<string>", line 504, in get_by_doi
  File "<string>", line 582, in _crossref_to_pybtex
AssertionError: Unknown type 'None'
```

My details:

```
✗ uname -a
Darwin MacBook-Air-136.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```

I installed betterbib via `pipx install betterbib`

**Comment by nschloe** [comment]
Try updating to betterbib 6. If the error persists, let me know and best attach a minimal bibtex file that reproduces the issue.

**Comment by nschloe** [comment]
Assuming this is fixed. Feel free to reopen/comment if the issue persists!
