### ISSUE TITLE
running into `HTTPError`

### ISSUE THREAD

**Issue by kjappelbaum** [texworld/betterbib#276]
with `betterbib=7.1.8` I run into 

```
Traceback (most recent call last):
  File "/Users/kevinmaikjablonka/miniconda3/bin/betterbib", line 5, in <module>
    from betterbib.cli import main
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/betterbib/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1, in <module>
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/betterbib/cli/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1, in <module>
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/betterbib/_agg/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1382, in <module>
  File "<string>", line 1378, in _8JTCB
  File "<string>", line 97, in _FXfTC
  File "<string>", line 1193, in _KJzH6
  File "<string>", line 92, in _0qa5Z
  File "<string>", line 1251, in _J4pmy
  File "<string>", line 103, in _0lGMU
  File "<string>", line 837, in _zRuzK
  File "<string>", line 722, in _C729Y
  File "<string>", line 762, in _fxmHL
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.keygen.sh/v1/accounts/{uuid}/actions/check-out
```

`slim` shows me that the license is supposed to be valid

**Comment by nschloe** [comment]
Could you upgrade to 7.1.9, and tell me the output of `betterbib vv`?

**Comment by kjappelbaum** [comment]
Thanks for the swift reply.


```
betterbib vv
Traceback (most recent call last):
  File "/Users/kevinmaikjablonka/miniconda3/bin/betterbib", line 5, in <module>
    from betterbib.cli import main
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/betterbib/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1, in <module>
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/betterbib/cli/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1, in <module>
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/betterbib/_agg/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1386, in <module>
  File "<string>", line 1382, in _u0Ybx
  File "<string>", line 97, in _FXfTC
  File "<string>", line 1193, in _KJzH6
  File "<string>", line 92, in _0qa5Z
  File "<string>", line 1251, in _J4pmy
  File "<string>", line 103, in _0lGMU
  File "<string>", line 837, in _zRuzK
  File "<string>", line 722, in _C729Y
  File "<string>", line 762, in _fxmHL
  File "/Users/kevinmaikjablonka/miniconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.keygen.sh/v1/accounts/{uuid}/actions/check-out
```

**Comment by nschloe** [comment]
Hm, that's not helping. Try
```
ppi betterbib
```

**Comment by kjappelbaum** [comment]
I now also reinstalled in a clean environment, still having the same issue. 

`ppi betterbib` yields 

```
ppi betterbib
Python 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ]
macOS 14.4

betterbib 7.1.9

bibtexparser 2.0.0b7 (1.4.1 available)
platformdirs 4.2.2
pylatexenc 2.10
python-package-info 0.0.4
requests 2.32.3
requests-cache 1.2.0
rich 13.7.1
rich-argparse 1.5.0
stonefish-license-manager 0.4.30
unidecode 1.3.8
x21 0.4.33 (0.5.1 available)
xmltodict 0.13.0
```


`slime` shows

```
Product        TeX World                                                                                                                                                                 │
Vendor         Monday Tech                                                                                                                                                               │
License ID     ****4                                                                                                                                      │
Usage type     Home/Academic                                                                                                                                                             │
Valid          True                                                                                                                                                                      │
User           kevin******                                                                                                                                                │
Created        2024-03-30                                                                                                                                                                │
Activations    1                                                                                                                                                                         │
Seats used     1/2                                                                                                                                                                       │
Machines       ******
```

**Comment by nschloe** [comment]
The `ppi` output shows Python 3.12, your above output Python 3.8. A conflict perhaps?

**Comment by kjappelbaum** [comment]
> 
The ppi output shows Python 3.12, your above output Python 3.8. A conflict perhaps?

sorry for the confusion. This is because I created a novel Python 3.12 environment in which I only installed `betterbibtex`

**Comment by kjappelbaum** [comment]
All the output in https://github.com/texworld/betterbib/issues/276#issuecomment-2147948527 was from the new env. 


Here again, 

```
ppi betterbib
Python 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ]
macOS 14.4

betterbib 7.1.9

bibtexparser 2.0.0b7 (1.4.1 available)
platformdirs 4.2.2
pylatexenc 2.10
python-package-info 0.0.4 (0.0.5 available)
requests 2.32.3
requests-cache 1.2.0
rich 13.7.1
rich-argparse 1.5.0
stonefish-license-manager 0.4.30
unidecode 1.3.8
x21 0.4.33 (0.5.1 available)
xmltodict 0.13.0
```


```
betterbib vv
Traceback (most recent call last):
  File "/Users/kevinmaikjablonka/miniconda3/envs/py312/bin/betterbib", line 5, in <module>
    from betterbib.cli import main
  File "/Users/kevinmaikjablonka/miniconda3/envs/py312/lib/python3.12/site-packages/betterbib/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1, in <module>
  File "/Users/kevinmaikjablonka/miniconda3/envs/py312/lib/python3.12/site-packages/betterbib/cli/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1, in <module>
  File "/Users/kevinmaikjablonka/miniconda3/envs/py312/lib/python3.12/site-packages/betterbib/_agg/__init__.py", line 2, in <module>
    x21.dex_24a(__file__)
  File "<string>", line 1386, in <module>
  File "<string>", line 1382, in _u0Ybx
  File "<string>", line 110, in _5Ramh
  File "<string>", line 863, in _q7lZz
  File "<string>", line 105, in _1rHYr
  File "<string>", line 921, in _j2OYu
  File "<string>", line 116, in _ZkhaU
  File "<string>", line 837, in _MdzKM
  File "<string>", line 722, in _rJwrL
  File "<string>", line 762, in _RymVL
  File "/Users/kevinmaikjablonka/miniconda3/envs/py312/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.keygen.sh/v1/accounts/******b/actions/check-out
```

**Comment by nschloe** [comment]
Could you please write a mail to support@mondaytech.com with the full details of the error message?
