### ISSUE TITLE
Error during sync, No idea what's going on.

### ISSUE THREAD

**Issue by Gabriel0402** [texworld/betterbib#277]
Warning: PubMed: Couldn't reliably parse name Alistair Steyn-Ross D
Warning: PubMed: Couldn't reliably parse name Bard Ermentrout G
Warning: PubMed: Couldn't reliably parse name Dos Santos F
Warning: PubMed: Couldn't reliably parse name Michael Wong KY
Warning: PubMed: Couldn't reliably parse name de Weerd P
Warning: PubMed: Couldn't reliably parse name van der Eerden J

Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/betterbib/bin/betterbib", line 8, in <module>
    sys.exit(main())
  File "<string>", line 1375, in _5y3P8
  File "<string>", line 1335, in _m4cke
  File "<string>", line 904, in _jwwX4
  File "<string>", line 919, in _H4QH3
  File "<string>", line 600, in _5uwyG
TypeError: 'NoneType' object is not iterable

**Comment by Gabriel0402** [comment]
7.1.16
