### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Gabriel0402** [texworld/betterbib#278]
Just upgrade from 4.5 to 7.1.10, everything does not work any more.

Warning: dblp: Unexpected field authors = {'author': [{'@pid': '82/1031',
'text': 'Xiaofu Wu'}, {'@pid': '23/8759', 'text': 'Suofei Zhang'}, {'@pid':
'29/5849-4', 'text': 'Quan Zhou 0004'}, {'@pid': '70/2539-1', 'text': 'Zhen Yang
0001'}, {'@pid': '49/4098', 'text': 'Chunming Zhao'}, {'@pid': '44/1633',
'text': 'Longin Jan Latecki'}]}
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/betterbib/bin/betterbib", line 8, in <module>
    sys.exit(main())
  File "<string>", line 1375, in _5y3P8
  File "<string>", line 1332, in _m4cke
  File "<string>", line 581, in _KauQo
  File "/Users/user/opt/anaconda3/envs/betterbib/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/user/opt/anaconda3/envs/betterbib/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/user/opt/anaconda3/envs/betterbib/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<string>", line 556, in _gsPsX
  File "<string>", line 419, in _j9k4F
  File "<string>", line 438, in _7xplb
AssertionError

**Comment by Gabriel0402** [comment]
upgrade to 7.1.16 solved the issue
