### ISSUE TITLE
more documentation on warnings and errors?

### ISSUE THREAD

**Issue by ah3243** [texworld/betterbib#279]
I'm running this with the pip package and am getting quite a few unusual warnings and errors. Is there more extensive documentation about the classes or what the errors mean?

This is a sample of what i get (and as far as i can tell non of those authors names are in my bibtex file...

```
  Unknown block type <class 'bibtexparser.model.DuplicateBlockKeyBlock'>
  Unknown block type <class 'bibtexparser.model.DuplicateBlockKeyBlock'>
  Unknown block type <class 'bibtexparser.model.DuplicateBlockKeyBlock'>
  Unknown block type <class 'bibtexparser.model.DuplicateBlockKeyBlock'>
  Syncing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Warning: PubMed: Couldn't reliably parse name van der Sande MAB
  Syncing... ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  14% 0:00:02Warning: posted-content is not a supported type
  Syncing... ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  23% 0:00:02
  Warning: journal-issue is not a supported type
  Warning: PubMed: Couldn't reliably parse name El Chemaly T
  Warning: PubMed: Couldn't reliably parse name Athayde Neves C
  Warning: dblp: Unexpected DBLP publication type `Books and Theses`
  Warning: PubMed: Couldn't reliably parse name De Menezes LP
  Warning: dblp: Unexpected DBLP publication type `Books and Theses`
  Warning: dblp: Unexpected DBLP publication type `Books and Theses`
  Warning: PubMed: Couldn't reliably parse name De Witt Jansen B
  Warning: PubMed: Couldn't reliably parse name Sivarajan Froelicher ES
```

then it'll fail with something like this:

```
Traceback (most recent call last):
  File "/Users/username/miniconda3/envs/latex/bin/betterbib", line 8, in <module>
    sys.exit(main())
  File "<string>", line 1442, in _z96Bg
  File "<string>", line 1400, in _pjhRZ
  File "<string>", line 1031, in _uHrIx
  File "/Users/username/miniconda3/envs/latex/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/username/miniconda3/envs/latex/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/username/miniconda3/envs/latex/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<string>", line 1003, in _3v2PY
  File "<string>", line 783, in _wDE7u
  File "<string>", line 908, in _HijpO
AssertionError: Unknown type 'None'
```

what do the above warnings and assertion error mean?

**Comment by nschloe** [comment]
Could you please attach the bib file or bib entry that produces the warnings/error?

**Comment by nschloe** [comment]
I just released 7.2.1 with various fixes. Could you please try and see if this works for you? If now, best post the offending bibfile.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time!
